name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'

    - name: Prepare git client
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Bump version
      run: |
        VERSION=$(npm version minor)
        echo "::set-env name=PACKAGE_VERSION::$VERSION"
        git push

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: Release ${{ env.PACKAGE_VERSION }}
        body: |
          read code ;)
        draft: false
        prerelease: false

    # - name: Bump version and push tag
    #   uses: anothrNick/github-tag-action@1.17.2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     WITH_V: true
    #     CUSTOM_TAG: env.PACKAGE_VERSION