name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'

    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - run: |
        VERSION=$(npm version minor)
        echo "::set-env name=PACKAGE_VERSION::$VERSION"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.PACKAGE_VERSION }}
        release_name: Release ${{ env.PACKAGE_VERSION }}
        body: |
          read code ;)
        draft: false
        prerelease: false

    # - name: Bump version and push tag
    #   uses: anothrNick/github-tag-action@1.17.2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     WITH_V: true
    #     CUSTOM_TAG: env.PACKAGE_VERSION